
    - require: "@djencks/antora-site-manifest"
      import_manifests:
        - primary_site_manifest_url: ./documentation/site-manifest.json
      local_urls: true
      # Turn on partial_components if you further restict source-watch to build less than the full subproject.
#      partial_components: true

    - require: '@djencks/antora-timer'
      log_level: info

  generator: '@djencks/antora-source-watch'