baseURL = "https://camel.apache.org/"
languageCode = "en-us"
title = "Apache Camel"
relativeURLs = true

[[menu.main]]
    name = "News"
    weight = 1
    identifier = "news"
    url = "/news/"

 [[menu.main]]
    name = "Documentation"
    identifier = "docs"
    weight = 2

[[menu.main]]
    name = "User manual"
    parent = "docs"
    weight = 1
    identifier = "manual"
    url = "/manual/latest/"

[[menu.main]]
    name = "Component reference"
    parent = "docs"
    weight = 2
    identifier = "components"
    url = "/manual/latest/"
