baseURL = "https://camel.apache.org/"
languageCode = "en-us"
title = "Apache Camel"
relativeURLs = true
disablePathToLower = true
staticDir = ["static", "documentation"]
disableKinds = ["taxonomyTerm"]
enableRobotsTXT = true
timeout = 300000

[blackfriday]
    nofollowLinks = true
    noreferrerLinks = true

[params]
    socialProfiles = ["https://twitter.com/ApacheCamel"]
    organizationLogo = "https://camel.apache.org/_/img/logo-d.svg"
    organizationDescription = "Apache Camel â„¢ is a versatile open-source integration framework based on known Enterprise Integration Patterns. Camel empowers you to define routing and mediation rules in a variety of domain-specific languages, including a Java-based Fluent API, Spring or Blueprint XML Configuration files, and a Scala DSL."

[caches]

    [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "12h"

    [caches.getcsv]
    dir = ":cacheDir/:project"
    maxAge = "12h"

[sitemap]
  filename = "sitemap-website.xml"

[[menu.main]]
    name = "Blog"
    weight = 2
    identifier = "blog"
    url = "/blog/"

[[menu.main]]
    name = "Documentation"
    identifier = "docs"
    weight = 4
    url = "/docs/"

[[menu.main]]
    name = "Community"
    identifier = "community"
    weight = 5

[[menu.main]]
    name = "Download"
    weight = 6
    identifier = "download"
    url = "/download/"

[module]

  [[module.mounts]]
    source = "documentation/_/data"
    target = "data"

[permalinks]
    blog = "blog/:year/:month/:filename/"
