[build]
  command = "(cd antora-ui-camel && yarn --non-interactive --frozen-lockfile install && yarn --non-interactive --frozen-lockfile build) && yarn --non-interactive --frozen-lockfile install && yarn --non-interactive --frozen-lockfile build"
